---
title: "Template"
format: html
editor: visual
---

## Idea

If the result of a *k-means* clustering run is "real", then the cluster centers should be consistent in different subsamples.

## Metric Calculation

```{r}
library(tidyverse)
library(rdist)

dat <- penguins %>% 
  select(bill_length_mm:body_mass_g) %>%
  drop_na() %>%
  mutate_all(scale) %>%
  as.matrix()

## We need a baseline to compare to

baseline_centers <- map(2:6, ~kmeans(dat, centers = .x)$centers)


## Function for "best" matchup of centers

center_similarity <- function(centers_1, centers_2) {
  
  all_dists <- cdist(centers_1, centers_2)
  
  best_dists <- apply(all_dists, 1, min)
  
  return(sum(best_dists))
  
}

## Measure distance from baseline for subsample

get_center_dist <- function(dat_sub, k, baseline) {
  
   temp <- kmeans(dat_sub, k)$centers
   
   center_similarity(temp, baseline)
  
}


```

## Experiments

```{r}

set.seed(1989)

## Arbitrarily chosen size - half of dataset
sub_n <- nrow(dat)/2

res <- c()
for (k in 2:6) {
  
  for (reps in 1:100){
    
    dat_sub <- dat[sample(1:nrow(dat), sub_n),]
    
    temp_dist <- get_center_dist(dat_sub, k, baseline_centers[[k-1]])

    res <- rbind(res, c("nclust" = k, "center_dist" = temp_dist))
  
  }
}
```

```{r}
res |>
  as_tibble() |>
  group_by(nclust) |> 
  summarize(mean(center_dist))
```


```{r}
res |> 
  ggplot() +
  aes(x = center_dist, y = factor(nclust)) +
  geom_density_ridges()
```

## Results

Maybe promising?  2 centers is behaving strangely, in that it's always super accurate.  But three is substantially smaller than 4 and 5... perhaps worth trying on other data, or looking into more.
